[package]
name = "circular_buffer_rs"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "circular_buffer_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
lazy_static = "1.4.0"
dashmap = "5.5.3"